// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehphs_iQslMPki6WXJRlMtIy7u_jI-ak',
    appId: '1:706953368540:web:742fcc61698d1d55ecb519',
    messagingSenderId: '706953368540',
    projectId: 'chatapp-c7f79',
    authDomain: 'chatapp-c7f79.firebaseapp.com',
    storageBucket: 'chatapp-c7f79.appspot.com',
    measurementId: 'G-WXG0GYD12R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaB3Dq8VR0IDFF3E24vcZVko51H5VOG8o',
    appId: '1:706953368540:android:a839ae54f291deafecb519',
    messagingSenderId: '706953368540',
    projectId: 'chatapp-c7f79',
    storageBucket: 'chatapp-c7f79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVu5PMGmJrgxsFy_9HBC9J_GUWLDntFzk',
    appId: '1:706953368540:ios:8386972112796ccaecb519',
    messagingSenderId: '706953368540',
    projectId: 'chatapp-c7f79',
    storageBucket: 'chatapp-c7f79.appspot.com',
    iosClientId: '706953368540-ep5qlou9bnuvr1jakt2ss15r9q8rt4ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
